export const USERS = [
  {
    id: "mansura",
    name: "Mansura",
    email: "mansura@gmail.com",
    bio: "Banladesh is my land",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "sojol",
    name: "SOJOL",
    email: "computerhouse008@gmail.com",
    bio: "Helllo Bangladesh",
    online: true,
    canMessage: false,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1757625520343",
  },
  {
    id: "admin",
    name: "admin",
    email: "admin@gmail.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "01828271177",
    name: "01828271177",
    email: "computeeerhouse008@gmail.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "Cout9mer123",
    name: "Cout9mer123",
    email: "gdjebdgx37@gmail.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "mosarrofhossain123",
    name: "mosarrofhossain123",
    email: "mosarrof@gmail.com",
    bio: "Ok",
    online: true,
    canMessage: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1757899952223",
  },
  {
    id: "bvcjhgfc654",
    name: "bvcjhgfc654",
    email: "jhdgfirgbg2@gmail.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "naima123",
    name: "naima123",
    email: "naima@gmail.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "dyxyw",
    name: "dyxyw",
    email: "pysuje@mailinator.com",
    bio: "yyyyt",
    online: true,
    canMessage: false,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1757953764869",
  },
  {
    id: "mewmew",
    name: "mewmew",
    email: "test@gmail.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1758131791680",
  },
  {
    id: "pawakin",
    name: "pawakin995@bitfami.com",
    email: "pawakin95@bitfami.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "asdf",
    name: "asdf",
    email: "emarancgea@gmial.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  {
    id: "asdfasd",
    name: "asdfasd",
    email: "aasdf@gmail.com",
    bio: "No bio available",
    online: true,
    canMessage: false,
    avatar: "https://i.postimg.cc/fRVdFSbg/e1ef6545-86db-4c0b-af84-36a726924e74.png",
  },
  // duplicate more items to simulate a larger list for lazy loading demo
  ...Array.from({ length: 100 }).map((_, i) => ({
    id: `user${i + 1}`,
    name: `Demo User ${i + 1}`,
    email: `demo${i + 1}@example.com`,
    bio: i % 3 === 0 ? "No bio available" : "Just another user",
    online: i % 2 === 0,
    canMessage: i % 5 === 0,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=" + (1000 + i),
  })),
];